Cray-HPE/docs-sat

docs/release_notes.md
Edit of release notes draft provided in the associated Jira.
I was going to include "known issues" in this PR, but Jira is down, so I can't reference our conversation on that ticket. I'll follow this up with that content in a new PR after Jira is back up.
Jira: [STP-3196](https://jira-pro.its.hpecorp.net:8443/browse/STP-3196)
=> STP-3196: add 2.3 release notes

docs/README.md, docs/release_notes.md
CRAYSAT-1494: Cherry-pick 2.3 release notes to 2.3 release branch
* Resolves [CRAYSAT-1494](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1494)
Docs were built using the CSM docs web builder and inspected for errors.
N/A
=> CRAYSAT-1494: Cherry-pick 2.3 release notes to 2.3 release branch

docs/release_notes.md
Add description of known issues in SAT 2.2 to release notes.
* Resolves [CRAYSAT-1493](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1493)
Build docs with csm-docs-html-builder and inspect for issues.
N/A
=> CRAYSAT-1493: Add known issues to SAT 2.2 release notes

docs/README.md, docs/release_notes.md
Add description of known issues in SAT 2.2 to release notes.
* Resolves [CRAYSAT-1493](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1493)
Build docs with csm-docs-html-builder and inspect for issues.
N/A
=> CRAYSAT-1493: Add known issues in SAT 2.2 to SAT 2.4 release notes

docs/release_notes.md
Add description of known issues in SAT 2.2 to release notes.
* Resolves [CRAYSAT-1493](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1493)
Build docs with csm-docs-html-builder and inspect for issues.
N/A
=> CRAYSAT-1493: Add known issues in SAT 2.2 to SAT 2.3 release notes

docs/README.md
Add a link to the 2.3 release notes to README.md on the integration branch.
=> CRAYSAT-1493: Add link to 2.3 release notes back to README.md

docs/README.md, docs/install.md, docs/release_notes.md
STP-3196: add 2.3 release notes (#11)
CRAYSAT-1487: Add documentation to set up external SAT
Merge pull request #12 from Cray-HPE/CRAYSAT-1487-setup-for-external-sat
CRAYSAT-1493: Add known issues to SAT 2.2 release notes
Merge pull request #15 from Cray-HPE/CRAYSAT-1493-known-issues-integration
CRAYSAT-1493: Add link to 2.3 release notes back to README.md
Merge pull request #19 from Cray-HPE/CRAYSAT-1493-2.3-link-integration
=> Merge from integration_2022-08-10_11.42 to main (Cray-HPE/docs-sat) 08-10

.github/workflows/license-check.yaml, docs/README.md
CRAYSAT-1535: Add license check configuration
Merge pull request #24 from Cray-HPE/CRAYSAT-1535-add-license-check
=> Merge from integration_2022-08-31_12.12 to main (Cray-HPE/docs-sat) 08-31

.spelling, docs/README.md, docs/release_notes.md
Added release notes documenting the changes in SAT 2.4 from the previous version SAT 2.3.
* Resolves [STP-3303](https://jira-pro.its.hpecorp.net:8443/browse/STP-3303)
* Change will also be needed in `release/2.4`
=> STP-3303: Add release notes for SAT 2.4 to integration

.spelling, docs/README.md, docs/release_notes.md
Added release notes documenting the changes in SAT 2.4 from the previous version SAT 2.3.
* Resolves [STP-3303](https://jira-pro.its.hpecorp.net:8443/browse/STP-3303)
=> STP-3303: Add release notes for SAT 2.4 to release/2.4

docs/install.md, docs/introduction.md
* Add sat jobstat to "sat dependencies" table.
* Add sat jobstat to table describing sat authentication types.
See commit message
* Part of CRAYSAT-1587
=> CRAYSAT-1587: Document sat jobstat command

LICENSE, rpm/README.md
Test Description: I tested the URL exists.
=> CASMINST-5808: Update link to SAT documentation RPM

.spelling, docs/README.md, docs/external_system.md, docs/install.md, docs/release_notes.md, docs/upgrade.md
- Include a high-level paragraph about IUF
- Add new section with product-specific configuration details that must be followed along with CSM IUF procedures
- Remove install and upgrade content that will reside in the CSM guide going forward
- Reorganize information in other folders and files based on this new setup
* Resolves [STP-3454](https://jira-pro.its.hpecorp.net:8443/browse/STP-3454)
* Future work required by [STP-3447](https://jira-pro.its.hpecorp.net:8443/browse/STP-3447)
* Merge after [PR #69]
=> STP-3454: Document IUF tool for SAT

.spelling, docs/README.md, docs/external_system.md, docs/install.md, docs/release_notes.md, docs/upgrade.md
- Include a high-level paragraph about IUF
- Add new section with product-specific configuration details that must be followed along with CSM IUF procedures
- Remove install and upgrade content that will reside in the CSM guide going forward
- Reorganize information in other folders and files based on this new setup
(cherry picked from commit b7882875e9773788c12f63bb93f6307e40bb0197)
* Resolves [STP-3454](https://jira-pro.its.hpecorp.net:8443/browse/STP-3454)
* Merge after [PR #75]
=> STP-3454: Document IUF tool for SAT for release/2.5

docs/introduction.md, docs/uninstall_and_downgrade.md, docs/usage/sat_bootprep.md
- Updated Alice recipe examples from 23.03 to 23.05
- Made minor wording revisions for clarity
* Resolves [STP-3420](https://jira-pro.its.hpecorp.net:8443/browse/STP-3420)
=> STP-3420: Update name of management NCN CFS config in integration

docs/introduction.md, docs/uninstall_and_downgrade.md, docs/usage/sat_bootprep.md
- Updated Alice recipe examples from 23.03 to 23.05
- Made minor wording revisions for clarity
(cherry picked from commit b08ec3b4a6f17b4ece412ce4de9fe5e1cb4d9e11)
* Resolves [STP-3420](https://jira-pro.its.hpecorp.net:8443/browse/STP-3420)
=> STP-3420: Update name of management NCN CFS config in release/2.5

docs/README.md, docs/external_system.md, docs/install.md, docs/introduction.md
- Clarify external system info now that it is its own section
- Streamline duplicated "Authenticate SAT Commands" information
- Shorten line lengths throughout
- Other minor clean-up work
* Resolves [STP-3522](https://jira-pro.its.hpecorp.net:8443/browse/STP-3522)
=> STP-3522: Clarify external system info in integration

docs/external_system.md, docs/install.md, docs/introduction.md, docs/release_notes/sat_2.5_release_notes.md, docs/upgrade.md, docs/usage/sat_and_iuf.md, docs/usage/sat_bootprep.md
- Consistently italicize guide titles
- Other minor clean-up work to finalize 23.04 content
* Resolves [STP-3578](https://jira-pro.its.hpecorp.net:8443/browse/STP-3578)
=> STP-3578: Italicize guides consistently in integration

.spelling, docs/install.md, docs/introduction.md, docs/release_notes/sat_2.2_release_notes.md, docs/release_notes/sat_2.4_release_notes.md, docs/release_notes/shasta_1.4_release_notes.md, docs/release_notes/shasta_1.5_release_notes.md, docs/uninstall_and_downgrade.md, docs/usage/change_bos_version.md
Revised information in our `.spelling` file. Eli Kamin had asked for review from a documentation perspective, and we are no longer using some of the terms on it. Please review the linked JIRA ticket for Eli's initial thoughts and my follow-up suggestions.
* Resolves [STP-3340](https://jira-pro.it.hpe.com:8443/browse/STP-3340)
Lint and spell checks
=> STP-3340: Revise spell check information in integration

.spelling, docs/install.md, docs/introduction.md, docs/release_notes/sat_2.2_release_notes.md, docs/release_notes/sat_2.4_release_notes.md, docs/release_notes/shasta_1.4_release_notes.md, docs/release_notes/shasta_1.5_release_notes.md, docs/uninstall_and_downgrade.md, docs/usage/change_bos_version.md
Revised information in our `.spelling` file. Eli Kamin had asked for review from a documentation perspective, and we are no longer using some of the terms on it. Please review the linked JIRA ticket for Eli's initial thoughts and my follow-up suggestions.
(cherry picked from commit 6c4ffca6d7bce2cff13f319fce602f3616fb863c)
* Resolves [STP-3340](https://jira-pro.it.hpe.com:8443/browse/STP-3340)
Lint and spell checks
=> STP-3340: Revise spell check information in release

.spelling, docs/release_notes/README.md, docs/release_notes/sat_2.6_release_notes.md
Add release notes for the SAT 2.6 release.
* Resolves [CRAYSAT-1737](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1737)
Build docs and check manually.
=> CRAYSAT-1737: Add SAT 2.6 release notes

.spelling, docs/about_sat/dependencies.md, docs/usage/sat_bootprep.md
Updated references to COS because of the COS replan effort.
* Resolves [STP-3690](https://jira-pro.it.hpe.com:8443/browse/STP-3690)
=> STP-3690: Update references to COS for Nov replan
