Cray-HPE/docs-sat

- .gitignore
- Jenkinsfile.github
- Makefile
- commit_count.sh
- docs-sat.spec
- rpm/README.md
- version.sh
This commit adds an RPM build of the SAT documentation.
Add a Makefile, RPM spec file, and .version file all used for the
building of the docs-sat RPM. The RPM will install all the markdown
files in the docs/ directory of this repository into
/usr/share/doc/sat/, except that docs/README.md is renamed
docs/index.md, and rpm/README.md is added in its place (i.e.,
installed at /usr/share/doc/sat/README.md).
This commit adds Jenkinsfile.github for building the RPM in a Jenkins
pipeline. The RPM is published to one of two locations depending on
whether the build is stable. For stable builds, the RPM is published
to: "sat-rpms/hpe/stable/sle-15sp3/docs-sat/X.Y/noarch/" where X and Y
are the major/minor version numbers of SAT (e.g. 2.4). Additionally,
when publishing a stable RPM, a version …
> CRAYSAT-1417: SAT documentation RPM

- docs/README.md
- docs/release_notes.md
This change cherry-picks the 2.3 release notes from integration onto the 2.4 release branch.
* Resolves [CRAYSAT-1494](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1494)
Docs were built using the CSM docs web builder and inspected for errors.
N/A
> CRAYSAT-1494: Add SAT 2.3 release notes to 2.4 release branch

- docs/install.md
This change adds documentation on how to set up SAT to work from an
external system. Documentation is limited to describing how to point SAT
at externally accessible API endpoints.
Co-authored-by: Ryan Haasken <77809410+haasken-hpe@users.noreply.github.com>
(cherry picked from commit 1433416b84a19d483e639bd0ae329dd6b073e45a)
* Resolves [CRAYSAT-1487](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1487)
Changes were already tested on integration branch by building with csm-docs-html-builder.
N/A
> CRAYSAT-1487: Cherry-pick external SAT setup guide to 2.4 release branch

- docs/introduction.md
* Add notes about SAT being automatically included in CSM 1.3.
* Document components that are not included in this "bundled" version.
* Specifically mention CFS configuration content.
* Resolves [CRAYSAT-1549](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1549)
* An additional PR will be needed to the release/2.4 branch.
* See also: https://github.com/Cray-HPE/docs-csm/pull/2366
Spell check and style check
> CRAYSAT-1549: Document SAT inclusion in CSM

- docs/install.md
To workaround CRAYSAT-1561, document running the
`update-mgmt-ncn-cfs-config.sh` script with the additional argument
`type=Node`. This will eliminate the warning messages that come from
querying CFS for configurations that apply to NodeBMCs.
* Resolves [CRAYSAT-1562](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1562)
* surtur
Tested this command during an install of SAT 2.4.11 on surtur.
Low risk doc change to reduce warnings.
> CRAYSAT-1562: Include "type=Node" in HSM query for CFS configurations

- docs/introduction.md
* Add notes about SAT being automatically included in CSM 1.3.
* Document components that are not included in this "bundled" version.
* Specifically mention CFS configuration content.
* Resolves [CRAYSAT-1549](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1549)
* See also: https://github.com/Cray-HPE/docs-sat/pull/23 and https://github.com/Cray-HPE/docs-csm/pull/2366
> CRAYSAT-1549: Document SAT inclusion in CSM - 2.4 release branch

- docs/README.md
This commit adds a missing link from the top-level README.md file to the subsection of introduction.md detailing SAT inclusion in CSM.
Test Description: After pushing this branch, I verified the link worked viewing the docs in GitHub.
> CRAYSAT-1572: Add missing link in README.md

- docs/release_notes.md
The usage.md file was renamed sat_bootprep.md, resulting in a broken link.
> CRAYSAT-1530: Address broken link from release notes

- .spelling
- docs/README.md
- docs/cne-install.md
- docs/cne_install.md
- docs/install.md
I added information about using the new CNE installer (`cne-install`) to upgrade SAT. This is the recommended method for upgrading SAT in Papaya, but the manual upgrade method does still work. The CNE installer cannot complete SAT installs in Papaya.
I chose not to include the upgrade process as part of the `install.md` file to simplify things. If the information was in this file, users would look there for three different processes (installing SAT, upgrading SAT manually, and upgrading SAT with cne-install). I think that would be too much information in one place and too much jumping around between the sub-processes.
* Resolves [STP-3310](https://jira-pro.its.hpecorp.net:8443/browse/STP-3310)
* Change will also be needed in `release/2.4`
Lint check, style check, spell check.
> STP-3310: Add SAT cne-install information

- .spelling
- docs/README.md
- docs/cne_install.md
- docs/install.md
I added information about using the new CNE installer (`cne-install`) to upgrade SAT. This is the recommended method for upgrading SAT in Papaya, but the manual upgrade method does still work. The CNE installer cannot complete SAT fresh installs in Papaya.
I chose not to include the upgrade process as part of the `install.md` file to simplify things. If the information was in this file, users would look there for three different processes (installing SAT, upgrading SAT manually, and upgrading SAT with cne-install). I think that would be too much information in one place and too much jumping around between the sub-processes.
* Resolves [STP-3310](https://jira-pro.its.hpecorp.net:8443/browse/STP-3310)
Lint check, style check, spell check.
> STP-3310: Add SAT cne-install information to release/2.4 branch

- .spelling
- docs/README.md
- docs/usage/README.md
- docs/usage/change_bos_version.md
- docs/usage/sat_bootprep.md
Added information on changing the BOS version. You can select the BOS version to use for individual commands with the `--bos-version` option. You can also configure the BOS version to use in the SAT config file.
* Resolves [STP-3353](https://jira-pro.its.hpecorp.net:8443/browse/STP-3353)
* Change will also be needed in `release/2.4`
> STP-3353: Add info on changing BOS version to integration branch

- docs/usage/sat_bootprep.md
This change documents `sat bootprep list-vars` for viewing the available variables when processing bootprep input files, without cloning the repository manually.
This change also refers the user to the `docs-csm` guide for viewing the default bootprep input files in order to reduce doc duplication.
* Resolves [CRAYSAT-1591](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1591)
Build docs, check for errors, and inspect built HTML.
None.
> CRAYSAT-1591: Document `list-vars`, refer to `docs-csm` for default files

- docs/usage/sat_bootprep.md
This commit adds three procedures to the SAT bootprep usage guide.
First, add a procedure explaining how to edit branch names in the input file. This could be useful if using working branches other than the default branches provided by the software recipe build.
Second, add a procedure explaining how to look up what configuration is used and how to rename it.
Finally, add a procedure explaining how to override a product's version via the `product_vars.yaml` file.
Test Description:
Ran all checks as a part of pull request process.
(cherry picked from commit 9e97ff424d58ac3c0040ea5028f902b0cec0ad84)
> CASMTRIAGE-4503: Add some helpful bootprep procedures

- docs/usage/sat_bootprep.md
Revised instructions on the following from [PR #49](https://github.com/Cray-HPE/docs-sat/pull/49):
- Editing branch names in the default bootprep input files
- Editing management CFS configuration names in the default bootprep input files
- Overriding a product's version via the `product_vars.yaml` file
* Resolves [STP-3402](https://jira-pro.its.hpecorp.net:8443/browse/STP-3402)
* Change will also be needed in `release/2.4`
> STP-3402: Change default recipe values in integration

- docs/cne_install.md
- docs/dashboards/SAT_Grafana_Dashboards.md
- docs/dashboards/SAT_Kibana_Dashboards.md
- docs/install.md
- docs/introduction.md
- docs/release_notes.md
- docs/usage/change_bos_version.md
- docs/usage/sat_bootprep.md
A new vanity URL is being used for the Papaya version of the Getting Started Guide. This URL has been updated throughout the SAT documentation. The new URL will not be live until the Papaya version of the Getting Started Guide is posted to the HPE Support Center with the official release. The new link is expected to break until then.
I also tried to create more consistency in how references and links are presented throughout. Here are my team's recommended guidelines:
- Use "refer to" for links/references outside sat-docs
- Use "see" for links/references within sat-docs
- Italicize guide titles we refer to
- Put section names of other guides we refer to in quotes
- Put topics names of other guides we refer to in bold
For CSM, it's ok to provide a general link to the documentation since …
> STP-3305: Update links to Getting Started Guide in integration

- docs/usage/sat_bootprep.md
Revised instructions on the following from [PR #50](https://github.com/Cray-HPE/docs-sat/pull/50):
- Editing branch names in the default bootprep input files
- Editing management CFS configuration names in the default bootprep input files
- Overriding a product's version via the `product_vars.yaml` file
* Resolves [STP-3402](https://jira-pro.its.hpecorp.net:8443/browse/STP-3402)
> STP-3402: Change default recipe values in release/2.4

- docs/cne_install.md
- docs/dashboards/SAT_Grafana_Dashboards.md
- docs/dashboards/SAT_Kibana_Dashboards.md
- docs/install.md
- docs/introduction.md
- docs/release_notes.md
- docs/usage/change_bos_version.md
- docs/usage/sat_bootprep.md
A new vanity URL is being used for the Papaya version of the Getting Started Guide. This URL has been updated throughout the SAT documentation. The new URL will not be live until the Papaya version of the Getting Started Guide is posted to the HPE Support Center with the official release. The new link is expected to break until then.
I also tried to create more consistency in how references and links are presented throughout. Here are my team's recommended guidelines:
- Use "refer to" for links/references outside sat-docs
- Use "see" for links/references within sat-docs
- Italicize guide titles we refer to
- Put section names of other guides we refer to in quotes
- Put topics names of other guides we refer to in bold
For CSM, it's ok to provide a general link to the documentation since …
> STP-3305: Update links to Getting Started Guide in release/2.4

- docs/install.md
Since public access to artifactory.algol60.net is being shut down, it is no longer possible to install SAT CSM Python Dependencies by setting PIP_EXTRA_INDEX_URL and installing the source tarball or binary distribution versions of SAT dependencies.
This commit updates the instructions for setting up SAT on an external system to provide steps to install the required packages from source rather than from artifactory.
Test Description: I ran the relevant steps locally and verified I could install SAT into a VirtualEnv without accessing artifactory.
See commit message
> CRAYSAT-1620: Changes for setting up SAT on an external system

- docs/install.md
- docs/introduction.md
- docs/usage/sat_bootprep.md
Beginning with the Alice release of the HPC CSM Software Recipe, the management NCN CFS configuration will be named
`management-{{recipe.version}}` where `recipe.version` is the version of the HPC CSM Software Recipe (currently planned to be 23.03). This single configuration will be applied both during management NCN image customization and node personalization. As a result its name is being changed to `management-{{recipe.version}}` in the default bootprep input file.
Update the SAT documentation to use this new naming convention. For now, we are assuming the Alice recipe version is going to be 23.03. If that changes, we will update it in the docs.
* Resolves [CRAYSAT-1610](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1610)
No testing was performed for this doc change. It's not …
> CRAYSAT-1610: Update name of management NCN CFS config

- docs/usage/sat_bootprep.md
Document that the playbook field in a layer of a CFS configuration in a `sat bootprep` input file now supports rendering as a Jinja2 template.
* Resolves [CRAYSAT-1648](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1648)
* Merge with https://github.com/Cray-HPE/sat/pull/88
* GitHub
Inspected markdown rendering in GitHub.
Low risk.
> CRAYSAT-1648: Document that playbook field supports Jinja2

- docs/usage/sat_bootprep.md
This commit adds detail on how hyphens are converted to underscores when reading software recipe variables.
Test Description: Read the document and checked spelling.
Co-authored-by: Jessica Dehn <109693479+jld-dehn-hpe@users.noreply.github.com>
(cherry picked from commit 222c6bde9399fd0b6e1e3ea2cb88df475a226d77)
See #70
> CRAYSAT-1662: Document automatic conversion of hyphens to underscores

- docs/README.md
- docs/external_system.md
- docs/install.md
- docs/introduction.md
- docs/release_notes.md
- docs/uninstall_and_downgrade.md
- docs/upgrade.md
I pulled the upgrade information, uninstall and downgrade information, and external system information from `install.md` into their own MD files. As part of the unified docs initiative, the installation and upgrade instructions for SAT need to be separated into two separate MD files. While working on this, it made sense to remove other distinct information so it's easier for users to find. This will also avoid uninstall and other information from being pulled into the unified docs effort where we don't want it.
* Resolves [STP-3439](https://jira-pro.its.hpecorp.net:8443/browse/STP-3439)
* Future work required by [STP-3447](https://jira-pro.its.hpecorp.net:8443/browse/STP-3447) and [STP-3455](https://jira-pro.its.hpecorp.net:8443/browse/STP-3455 …
> STP-3439: Separate install.md information

- docs/README.md
- docs/external_system.md
- docs/install.md
- docs/introduction.md
- docs/release_notes.md
- docs/uninstall_and_downgrade.md
- docs/upgrade.md
I pulled the upgrade information, uninstall and downgrade information, and external system information from `install.md` into their own MD files. As part of the unified docs initiative, the installation and upgrade instructions for SAT need to be separated into two separate MD files. While working on this, it made sense to remove other distinct information so it's easier for users to find. This will also avoid uninstall and other information from being pulled into the unified docs effort where we don't want it.
(cherry picked from commit dd03e65ab74cd6c24cbb2984ae46c69396221226)
* Resolves [STP-3439](https://jira-pro.its.hpecorp.net:8443/browse/STP-3439)
* Future work required by [STP-3454](https://jira-pro.its.hpecorp.net:8443/browse/STP-3454)
* Merge after PR #74 
Lint check and spell …
> STP-3439: Separate install.md information in release/2.5

- docs-product-manifest.yaml.in
- docs-sat.spec
Add the file `docs-product-manifest.yaml` to the RPM and substitute in the version of the docs-sat RPM into the file. It's not clear what this version is really being used for, but we are adding it here and making sure it matches the version of the docs, which is generated from a tag.
* Part of [STP-3447](https://jira-pro.its.hpecorp.net:8443/browse/STP-3447)
* Jenkins and locally on macbook
Pushed and let Jenkins build RPM. Downloaded RPM, extracted with
`rpm2cpio` and `cpio -idvmu`, and then verified inclusion of
`docs-product-manifest.yaml` and the correct version substitution.## Risks and Mitigations
> STP-3447: Add docs-product-manifest.yaml to RPM and substitute version

- docs-product-manifest.yaml.in
- docs-sat.spec
Add a manifest that defines the behavior for unifying docs across all CSM-based products. Add the file `docs-product-manifest.yaml` to the RPM and substitute in the version of the docs-sat RPM into the file. It's not clear what this version is really being used for, but we are adding it here and making sure it matches the version of the docs, which is generated from a tag.
* Resolves [STP-3447](https://jira-pro.its.hpecorp.net:8443/browse/STP-3447)
Pushed and let Jenkins build RPM. Downloaded RPM, extracted with `rpm2cpio` and `cpio -idvmu`, and then verified inclusion of `docs-product-manifest.yaml` and the correct version substitution.
> STP-3447: Add docs-product-manifest.yaml file to integration

- docs-product-manifest.yaml.in
- docs-sat.spec
Add a manifest that defines the behavior for unifying docs across all CSM-based products. Add the file `docs-product-manifest.yaml` to the RPM and substitute in the version of the docs-sat RPM into the file. It's not clear what this version is really being used for, but we are adding it here and making sure it matches the version of the docs, which is generated from a tag.
* Resolves [STP-3447](https://jira-pro.its.hpecorp.net:8443/browse/STP-3447)
Pushed and let Jenkins build RPM. Downloaded RPM, extracted with `rpm2cpio` and `cpio -idvmu`, and then verified inclusion of `docs-product-manifest.yaml` and the correct version substitution.
> STP-3447: Add docs-product-manifest.yaml file to release/2.5

- docs/install.md
In the `release/2.4` branch of the docs, it says "In SAT 2.4 and newer" when referencing `cne-install`. This is no longer true with the new IUF tool for Alice. It should just be "in SAT 2.4" for line 24 of the `install.md` file.
* Resolves [STP-3519](https://jira-pro.its.hpecorp.net:8443/browse/STP-3519)
> STP-3519: Update cne-install reference in release/2.4

- docs/usage/sat_bootprep.md
Document added support to `sat bootprep` that allows users to specify a filter string prefix when using multiple images or recipes from a product in the product catalog.
* Partly resolves [STP-3470](https://jira-pro.its.hpecorp.net:8443/browse/STP-3470)
**Note:** My plan is to separate the work required in [STP-3470](https://jira-pro.its.hpecorp.net:8443/browse/STP-3470) into four separate PRs for integration so that the information is easier to review. Once these are approved, I'll cherry pick all changes as one PR to `release/2.5`.
> STP-3470: Add filter string prefix info to integration

- docs/README.md
- docs/introduction.md
- docs/release_notes.md
- docs/uninstall_and_downgrade.md
- docs/usage/sat_bootprep.md
- Removed the "active" column from `sat showrev` for SAT 2.5. It is still possible to do all the same stuff that "activate" did even with the removal of this column (with the exception of actually updating the value in that column).
- Removed examples and references to the "active" column and "activate" wording throughout.
- Updated Alice recipe number throughout
* Resolves [STP-3520](https://jira-pro.its.hpecorp.net:8443/browse/STP-3520)
> STP-3520: Remove active info for `sat showrev` in integration

- docs/usage/sat_bootprep.md
Added information about the new summary output for `sat bootprep run`.
* Partly resolves [STP-3470](https://jira-pro.its.hpecorp.net:8443/browse/STP-3470)
**Note:** My plan is to separate the work required in [STP-3470](https://jira-pro.its.hpecorp.net:8443/browse/STP-3470) into four separate PRs for integration so that the information is easier to review. Once these are approved, I'll cherry pick all changes as one PR to `release/2.5`.
> STP-3470: Add information about `sat bootprep run` summary output to integration

- .spelling
- docs/usage/change_bos_version.md
The default BOS version used by `sat` commands is now v2. Update the docs to state this. Update the procedure for changing the version to show examples of changing the BOS version from v2 back to v1.
* Resolves [CRAYSAT-1700](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1700)
* The actual default value change is here: https://github.com/Cray-HPE/sat/pull/115
N/A
Low risk. The admin can always change back.
> CRAYSAT-1700: Change default BOS version used by SAT to v2

- docs/README.md
- docs/release_notes.md
- docs/usage/README.md
- docs/usage/sat_and_iuf.md
- docs/usage/sat_bootprep.md
- Created new SAT and IUF topic discussing the relationship between the two and important information relating to both
- Revised SAT bootprep topic to reflect variable changes in SAT 2.5 and clarify information
- Renamed section titles to remove gerunds
* Partly resolves [STP-3470](https://jira-pro.its.hpecorp.net:8443/browse/STP-3470)
**Note:** My plan is to separate the work required in [STP-3470](https://jira-pro.its.hpecorp.net:8443/browse/STP-3470) into four separate PRs for integration so that the information is easier to review. Once these are approved, I'll cherry pick all changes as one PR to `release/2.5`.
> STP-3470: Clarify SAT 2.5 and IUF relationship in integration

- docs/README.md
- docs/release_notes.md
- docs/usage/README.md
- docs/usage/sat_and_iuf.md
- docs/usage/sat_bootprep.md
- Added information on the new `--limit` option for `sat bootprep run`. This option restricts the creation of CFS configurations, IMS images, and BOS session templates into separate stages.
(cherry picked from commit https://github.com/Cray-HPE/docs-sat/commit/96593f94fbfdf19c6886ca4df7c3be14134c5a7c)
- Document added support to `sat bootprep` that allows users to specify a filter string prefix when using multiple images or recipes from a product in the product catalog.
(cherry picked from commit https://github.com/Cray-HPE/docs-sat/commit/a827bec143752137d899c929cb7e0e04d729302d)
- Added information about the new summary output for `sat bootprep run`.
(cherry picked from commit https://github.com/Cray-HPE/docs-sat/commit/38147d29415af237870a5972f3865a34449e08fc)
- Created new SAT and IUF …
> STP-3470: Add `sat bootprep` changes to release/2.5

- docs/README.md
- docs/external_system.md
- docs/install.md
- docs/introduction.md
- Clarify external system info now that it is its own section
- Streamline duplicated "Authenticate SAT Commands" information
- Shorten line lengths throughout
- Other minor clean-up work
(cherry picked from commit 67ec8970068d13585cb07d48372fa9ecc625c6f8)
* Resolves [STP-3522](https://jira-pro.its.hpecorp.net:8443/browse/STP-3522)
> STP-3522: Clarify external system info in release/2.5

- docs/release_notes/sat_2.5_release_notes.md
Realized we need to update the `sat` version in our 2.5 release notes because of Ryan's PR for CRAYSAT-1705. I was able to add this as another commit to the integration branch since my PR is still open, but I'm creating a new PR here.
Resolves [CRAYSAT-1705](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1705)
> CRAYSAT-1705: Update `sat` version in release notes

- docs/external_system.md
- docs/install.md
- docs/introduction.md
- docs/release_notes/sat_2.5_release_notes.md
- docs/upgrade.md
- docs/usage/sat_and_iuf.md
- docs/usage/sat_bootprep.md
- Consistently italicize guide titles
- Other minor clean-up work to finalize 23.04 content
(cherry picked from commit 7c35f841090f2eaab7e058dbab7ee23774bdd647)
* Resolves [STP-3578](https://jira-pro.its.hpecorp.net:8443/browse/STP-3578)
> STP-3578: Italicize guides consistently in release branch

- docs/introduction.md
- docs/uninstall_and_downgrade.md
Alice is officially releasing this week as recipe 23.05. Updating a few minor places in our documentation that reference the recipe as 23.04.
Change will also be needed in `release/2.5`
> Update Alice release number to 23.05

- docs/introduction.md
This change removes references to CRUS from the SAT documentation since CRUS is being removed from CSM.
* Resolves [CRAYSAT-1670](https://jira-pro.its.hpecorp.net:8443/browse/CRAYSAT-1670)
Build docs.
> CRAYSAT-1670: Remove references to CRUS

- docs/uninstall_and_downgrade.md
The functionality for `prodmgr activate` (switching between SAT versions) is being deprecated. I added a note with this information to the relevant section for SAT 2.6. I also did a search throughout the rest of the guide, and I don't think anything else needs to be changed until the functionality of this command is completely removed in a future release.
* Resolves [STP-3551](https://jira-pro.it.hpe.com:8443/browse/STP-3551)
> STP-3551: Note deprecation of `prodmgr activate` in integration

- docs/uninstall_and_downgrade.md
The functionality for `prodmgr activate` (switching between SAT versions) is being deprecated. I added a note with this information to the relevant section for SAT 2.6. I also did a search throughout the rest of the guide, and I don't think anything else needs to be changed until the functionality of this command is completely removed in a future release.
(cherry picked from commit eec43aa0da0ef451b5e39eb667395c46c0337bd7)
* Resolves [STP-3551](https://jira-pro.it.hpe.com:8443/browse/STP-3551)
> STP-3551: Note deprecation of `prodmgr activate` in release

- docs/README.md
- docs/install.md
- docs/usage/README.md
- docs/usage/multi-tenancy.md
This change adds information on how the tenant name can be configured and links it from the installation instructions.
* Resolves [CRAYSAT-1726](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1726)
Build docs and check for correctness.
> CRAYSAT-1726: Add information about multitenancy

- docs/external_system.md
- docs/install.md
In our instructions for `sat auth`, we need to add a link to better information in `docs-csm` about Keycloak and admin roles.
* Resolves [STP-3105](https://jira-pro.it.hpe.com:8443/browse/STP-3105)
> STP-3105: Add reference to Keycloak account info (integration)

- docs/external_system.md
- docs/install.md
In our instructions for `sat auth`, we need to add a link to better information in `docs-csm` about Keycloak and admin roles.
(cherry picked from commit 98c59a82cf367685a6c820f01f4573d5ccfa3255)
Resolves [STP-3105](https://jira-pro.it.hpe.com:8443/browse/STP-3105)
> STP-3105: Add reference to Keycloak account info (2.6)

- .github/workflows/backport.yml
- .github/workflows/license-check.yaml
Add the backport GitHub Actions workflow. This will allow us to backport changes from one branch to another using a comment like "/backport branch_name". For example, to backport commits from a PR to integration to the `release/2.6` branch, the following comment can be added.
> /backport release/2.6
Marking related to CRAYSAT-1734 since that is the first place I plan to use it to backport a change from integration to release/2.6.
* `<development system>`
* Virtual Shasta
Can't test the GitHub Actions workflow until it is merged to our default branch.
No
> CRAYSAT-1734: Add the backport GitHub Actions workflow

- .spelling
- docs/usage/sat_bootprep.md
Document the newly added `arch` field that can be specified at the
boot-set level in the BOS session templates defined in the `sat
bootprep` input file.
Test Description:
Tested modified bootprep input files passed schema validation with the
latest development version of the cray-sat container image.
Add documentation on how to use the `arch` and `wildcard` filtering on
base images or recipes provide by a product.
The `wildcard` functionality was added a little while ago, while the
`arch` functionality was just added by CRAYSAT-1718.
Provide examples that are similar to actual use cases that an admin will
encounter when looking at our default `sat bootprep` input files
delivered with the `hpc-csm-software-recipe` release distribution.
Test Description:
Tested modified bootprep input files …
> CRAYSAT-1734: Update bootprep usage docs for multi-arch support

- docs/about_sat/command_authentication.md
- docs/about_sat/sat_in_csm.md
- docs/about_sat/view_sat_docs.md
- docs/dashboards/SAT_Kibana_Dashboards.md
- docs/external_system.md
- docs/install.md
- docs/release_notes/sat_2.2_release_notes.md
- docs/release_notes/sat_2.4_release_notes.md
- docs/release_notes/sat_2.5_release_notes.md
- docs/release_notes/sat_2.6_release_notes.md
- docs/uninstall_and_downgrade.md
- docs/upgrade.md
- docs/usage/change_bos_version.md
- docs/usage/multi-tenancy.md
- docs/usage/sat_and_iuf.md
- docs/usage/sat_bootprep.md
Sarah did a copy/edit of SAT as part of one of her bold goals. This PR adds her suggested changes to improve the documentation.
* Resolves [STP-3680](https://jira-pro.it.hpe.com:8443/browse/STP-3680)
> STP-3680: Minor edits to improve documentation

- docs/about_sat/dependencies.md
- docs/usage/sat_bootprep.md
CNE is being renamed before release to User Services Software (USS). Updating references in `docs-sat` to match this change. Initial rename changes were made in PR #125.
* Resolves [STP-3731](https://jira-pro.it.hpe.com:8443/browse/STP-3731)
> STP-3731: Rename CNE references to USS

- docs/about_sat/dependencies.md
Add several missing services to `sat status` section of "SAT Dependencies" topic, and fix the incorrect service dependencies under the `sat slscheck` command.
* Resolves [CRAYSAT-1790](https://jira-pro.it.hpe.com:8443/browse/CRAYSAT-1790)
* The same change is being made in docs-csm here: https://github.com/Cray-HPE/docs-csm/pull/4542
> CRAYSAT-1790: Add missing services to SAT Dependencies
